version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stem_center
      MYSQL_USER: tien
      MYSQL_PASSWORD: Lz8p#Wq9Bv!x3Rs@T1uE
    volumes:
      - mysql-data:/var/lib/mysql

  bright_way:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stem-center-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # ✅ DATABASE_URL đã được URL-encode password đặc biệt
      DATABASE_URL: mysql://tien:Lz8p%23Wq9Bv%21x3Rs%40T1uE@db:3306/stem_center

      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: tien
      MYSQL_PASSWORD: Lz8p#Wq9Bv!x3Rs@T1uE
      MYSQL_DATABASE: stem_center

      NODE_ENV: development
      PORT: 5000

      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123456

      CLOUDINARY_CLOUD_NAME: your_cloud_name
      CLOUDINARY_API_KEY: your_api_key
      CLOUDINARY_API_SECRET: your_api_secret

      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: your_email@gmail.com
      SMTP_PASS: your_app_password

      JWT_SECRET: your_super_secret_jwt_key_here
      SESSION_SECRET: your_session_secret_key_here

      BASE_URL: http://localhost:5000
      FRONTEND_URL: http://localhost:5000

      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100

      LOG_LEVEL: info
      LOG_FILE: logs/app.log

      DEFAULT_PAGINATION_LIMIT: 10
      MAX_PAGINATION_LIMIT: 100

      ENABLE_REGISTRATION: true
      ENABLE_COMMENTS: false
      ENABLE_NEWSLETTER: true

    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  mysql-data:
