name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker compose build bright_way
          docker compose push bright_way

  deploy-service:
    runs-on: self-hosted
    needs: [build-image]
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Down Server and remove old image
        run: docker compose -f docker-compose.yaml -p bright_way down --rmi all
        continue-on-error: true

      - name: Pull new image
        run: docker compose -f docker-compose.yaml pull

      - name: Deploy container
        run: docker compose -f docker-compose.yaml -p tradiva_backend up -d
